*&----------------------------------------------------------------------
*& Include ZWS900000300001
*& User    OERTEN
*& Date    27.04.2020
*&----------------------------------------------------------------------

*&----------------------------------------------------------------------
*& THIS INCLUDE IS GENERATED BY THE WORKFLOW BUILDER.
*& NEVER CHANGE IT MANUALLY, PLEASE!
*&----------------------------------------------------------------------

*&----------------------------------------------------------------------
*&      Module  IMPORT_DATA_0001  OUTPUT
*&----------------------------------------------------------------------
MODULE IMPORT_DATA_0001 OUTPUT.

  PERFORM IMPORT_DATA_0001
     CHANGING
        PERNR.

ENDMODULE.                 " IMPORT_DATA_0001  OUTPUT

*&----------------------------------------------------------------------
*&      Module  EXPORT_DATA_0001  INPUT
*&----------------------------------------------------------------------
MODULE EXPORT_DATA_0001 INPUT.

  PERFORM EXPORT_DATA_0001
     USING
        PERNR.

ENDMODULE.                 " EXPORT_DATA_0001  INPUT


*&---------------------------------------------------------------------*
*&      Form  IMPORT_DATA_0001
*&---------------------------------------------------------------------*
 FORM import_data_0001
   CHANGING ps_data_structure TYPE any.

* move data from container to the structure
  CALL FUNCTION 'SWY_CONTAINER_TO_STRUCTURE'
    CHANGING
      data_structure = ps_data_structure.

 ENDFORM.                               " IMPORT_DATA_0001

*&---------------------------------------------------------------------*
*&      Form  EXPORT_DATA_0001
*&---------------------------------------------------------------------*
 FORM export_data_0001
   USING ps_data_structure TYPE any.

* move data from the structure to the container
  CALL FUNCTION 'SWY_STRUCTURE_TO_CONTAINER'
    CHANGING
      data_structure = ps_data_structure.

 ENDFORM.                               " EXPORT_DATA_0001
