*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 10.04.2020 at 15:36:26
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZOE_V001........................................*
FORM GET_DATA_ZOE_V001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOE_T001 WHERE
(VIM_WHERETAB) .
    CLEAR ZOE_V001 .
ZOE_V001-MANDT =
ZOE_T001-MANDT .
ZOE_V001-BUKRS =
ZOE_T001-BUKRS .
ZOE_V001-BUTXT =
ZOE_T001-BUTXT .
<VIM_TOTAL_STRUC> = ZOE_V001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOE_V001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOE_V001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOE_V001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOE_T001 WHERE
  BUKRS = ZOE_V001-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZOE_T001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOE_T001 WHERE
  BUKRS = ZOE_V001-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOE_T001.
    ENDIF.
ZOE_T001-MANDT =
ZOE_V001-MANDT .
ZOE_T001-BUKRS =
ZOE_V001-BUKRS .
ZOE_T001-BUTXT =
ZOE_V001-BUTXT .
    IF SY-SUBRC = 0.
    UPDATE ZOE_T001 ##WARN_OK.
    ELSE.
    INSERT ZOE_T001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOE_V001-UPD_FLAG,
STATUS_ZOE_V001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZOE_V001.
  SELECT SINGLE * FROM ZOE_T001 WHERE
BUKRS = ZOE_V001-BUKRS .
ZOE_V001-MANDT =
ZOE_T001-MANDT .
ZOE_V001-BUKRS =
ZOE_T001-BUKRS .
ZOE_V001-BUTXT =
ZOE_T001-BUTXT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOE_V001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOE_V001-BUKRS TO
ZOE_T001-BUKRS .
MOVE ZOE_V001-MANDT TO
ZOE_T001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOE_T001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOE_T001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOE_T001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZOE_V002........................................*
FORM GET_DATA_ZOE_V002.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOE_T002 WHERE
(VIM_WHERETAB) .
    CLEAR ZOE_V002 .
ZOE_V002-MANDT =
ZOE_T002-MANDT .
ZOE_V002-BUKRS =
ZOE_T002-BUKRS .
ZOE_V002-IBAN =
ZOE_T002-IBAN .
ZOE_V002-DATUM =
ZOE_T002-DATUM .
ZOE_V002-UZEIT =
ZOE_T002-UZEIT .
<VIM_TOTAL_STRUC> = ZOE_V002.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOE_V002 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOE_V002.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOE_V002-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOE_T002 WHERE
  BUKRS = ZOE_V002-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZOE_T002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOE_T002 WHERE
  BUKRS = ZOE_V002-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOE_T002.
    ENDIF.
ZOE_T002-MANDT =
ZOE_V002-MANDT .
ZOE_T002-BUKRS =
ZOE_V002-BUKRS .
ZOE_T002-IBAN =
ZOE_V002-IBAN .
ZOE_T002-DATUM =
ZOE_V002-DATUM .
ZOE_T002-UZEIT =
ZOE_V002-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE ZOE_T002 ##WARN_OK.
    ELSE.
    INSERT ZOE_T002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOE_V002-UPD_FLAG,
STATUS_ZOE_V002-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZOE_V002.
  SELECT SINGLE * FROM ZOE_T002 WHERE
BUKRS = ZOE_V002-BUKRS .
ZOE_V002-MANDT =
ZOE_T002-MANDT .
ZOE_V002-BUKRS =
ZOE_T002-BUKRS .
ZOE_V002-IBAN =
ZOE_T002-IBAN .
ZOE_V002-DATUM =
ZOE_T002-DATUM .
ZOE_V002-UZEIT =
ZOE_T002-UZEIT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOE_V002 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOE_V002-BUKRS TO
ZOE_T002-BUKRS .
MOVE ZOE_V002-MANDT TO
ZOE_T002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOE_T002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOE_T002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOE_T002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
